import { SubscriberArgs } from "@medusajs/framework";
import { Modules, ContainerRegistrationKeys } from "@medusajs/utils";

import { FINANCE_MODULE } from "../../../modules/finance";
import { createCreditMemoInQb } from "../client";
import {
  processPaymentCaptureInQb,
  ensureCustomerInQb,
  getBusinessDateString,
} from "../order-flow-core";
import {
  resolveQbPaymentMethodForPayment,
  sanitizeToQbPaymentMethod,
} from "../payment-method-sanitizer";
import {
  coalesceIfInFlight,
  writePipelineRow,
  cacheEditSequence,
  skipPaymentRowByReference,
} from "../qb-pipeline";

const LOG_PREFIX = "[QB-POS-PAYMENT]";
const ENABLED = process.env.QB_ORDER_FLOW_ENABLED === "true";

export async function handlePosPaymentCreated({
  event,
  container,
}: SubscriberArgs<any>) {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER);

  if (!ENABLED) {
    logger.info(
      `${LOG_PREFIX} ⏭️ QB_ORDER_FLOW_ENABLED=false — skipping ${event.name}`
    );
    return;
  }

  const paymentId = event.data.id;
  if (!paymentId) return;

  logger.info(
    `${LOG_PREFIX} 📥 Received ${event.name} for payment ${paymentId}`
  );

  // Coalesce rapid saves: if a payment op is already in-flight for this paymentId,
  // mark next_payload and return — consolidator will re-submit after current op confirms.
  // Payments use reference_id (not order_id) as the pipeline key.
  const coalescedPay = await coalesceIfInFlight(null, paymentId, "payment");
  if (coalescedPay) {
    logger.info(
      `${LOG_PREFIX} ⏸ Payment in-flight for ${paymentId} — coalesced as next submit`
    );
    return;
  }

  try {
    const query = container.resolve(ContainerRegistrationKeys.QUERY);
    const financeService = container.resolve(FINANCE_MODULE) as any;
    const customerModule = container.resolve(Modules.CUSTOMER);

    // 1. Fetch the Payment
    const {
      data: [payment],
    } = await query.graph({
      entity: "customer_payment",
      fields: ["*", "metadata"],
      filters: { id: paymentId },
    });

    if (!payment) {
      logger.warn(`${LOG_PREFIX} ⚠️ Payment not found: ${paymentId}`);
      return;
    }

    // Only process POS generated ones (exclude ACH synced from QBO if we ever add that)
    if (payment.source !== "pos") {
      logger.info(`${LOG_PREFIX} Skipping non-POS payment: ${payment.source}`);
      return;
    }

    // GUARD: 'credit_memo' typed payments are already synced natively by the completion endpoint with full product lines.
    if (payment.type === "credit_memo") {
      logger.info(
        `${LOG_PREFIX} ⏭️ Skipping payment sync: payment.type is '${payment.type}'. Full Credit Memo already generated by POS Returns module.`
      );
      return;
    }

    // IDEMPOTENCY: skip if already synced or in-flight (prevents duplicate QB operations on server restart / event replay)
    const existingSyncStatus = payment.metadata?.qb_sync_status as
      | string
      | undefined;
    if (existingSyncStatus === "synced" || existingSyncStatus === "creating") {
      logger.info(
        `${LOG_PREFIX} ⏭️ Skipping: payment ${paymentId} already has qb_sync_status='${existingSyncStatus}'`
      );
      return;
    }

    // SALES RECEIPT GUARD: payments captured inside a QB Sales Receipt are already
    // embedded in that transaction — creating a separate ReceivePayment would duplicate it.
    // Matches 4 flags set by the invoice route or SR handler at various stages.
    const srEmbedded =
      payment.metadata?.qb_source === "sales_receipt" ||
      payment.metadata?.is_sales_receipt_payment === true ||
      payment.metadata?.qb_sync_status === "pending_sr";
    if (srEmbedded) {
      logger.info(
        `${LOG_PREFIX} ⏭️ Skipping: payment ${paymentId} is embedded in a Sales Receipt — no standalone ReceivePayment needed`
      );
      // Defensive: also skip any stale pipeline row that may still be waiting for this payment.
      try {
        const n = await skipPaymentRowByReference(
          paymentId,
          "Payment embedded in Sales Receipt — standalone row not needed"
        );
        if (n > 0)
          logger.info(
            `${LOG_PREFIX} ⏭️ Skipped ${n} stale pipeline row(s) for payment ${paymentId}`
          );
      } catch (e: any) {
        logger.warn(
          `${LOG_PREFIX} Could not skip stale pipeline row for ${paymentId}: ${e.message}`
        );
      }
      return;
    }

    // $0 ANCHOR GUARD: credit-only transactions create a $0 anchor payment as a transaction
    // envelope for the UI. There is nothing to record in QB for a $0 payment.
    if (Number(payment.amount) === 0) {
      logger.info(
        `${LOG_PREFIX} ⏭️ Skipping: payment ${paymentId} has amount=0 (credit-only transaction anchor — no QB entry needed)`
      );
      return;
    }

    const orderId = payment.metadata?.order_id;
    const orderDisplayId = payment.metadata?.order_display_id;

    if (!orderId) {
      logger.warn(
        `${LOG_PREFIX} ⚠️ Payment ${paymentId} has no order_id in metadata, cannot map to QB completely.`
      );
    }

    // 2. Resolve Customer List ID
    let customer = null;
    let qbCustomerId = null;

    if (payment.customer_id) {
      customer = await customerModule.retrieveCustomer(payment.customer_id, {
        relations: ["addresses"],
      });
      qbCustomerId = customer.metadata?.qb_list_id;
    }

    if (!qbCustomerId && customer) {
      logger.info(
        `${LOG_PREFIX} Customer ${customer.id} not in QB yet. Ensuring...`
      );
      const custResult = await ensureCustomerInQb(
        customer,
        customerModule,
        (msg) => logger.info(msg)
      );
      if (custResult.success) {
        qbCustomerId = custResult.qbCustomerId;
      } else {
        logger.error(
          `${LOG_PREFIX} ❌ Failed to ensure customer in QB: ${custResult.error}`
        );
        return;
      }
    }

    if (!qbCustomerId) {
      logger.error(
        `${LOG_PREFIX} ❌ Could not determine qb_list_id for payment ${paymentId}`
      );
      return;
    }

    const depositType = payment.metadata?.deposit_type;
    const invoiceIds = payment.metadata?.invoices_affected as
      | string[]
      | undefined;

    // Medusa-side reference (for pipeline tracking only — not sent to QB)
    const medusaPayRef = payment.display_id
      ? `PAY-${payment.display_id}`
      : null;

    // Memo for QB (human-readable note, not a ref number)
    const payDisplayId = payment.display_id ? `${payment.display_id}` : null;
    let memo: string | undefined;
    if (depositType === "INVOICE" && invoiceIds?.length) {
      const invoiceFriendlyIds = payment.metadata
        ?.invoices_affected_friendly as string[] | undefined;
      if (invoiceFriendlyIds?.length) {
        memo = payDisplayId
          ? `Payment ${payDisplayId} for Invoice ${invoiceFriendlyIds.join(", ")}`
          : `Payment for Invoice ${invoiceFriendlyIds.join(", ")}`;
      }
    }
    if (!memo) {
      if (orderId || orderDisplayId) {
        memo = payDisplayId
          ? `Payment ${payDisplayId} for Order ${orderDisplayId || orderId}`
          : `Payment for Order ${orderDisplayId || orderId}`;
      } else {
        memo = payDisplayId
          ? `Payment ${payDisplayId} — Customer Deposit`
          : `Customer Deposit`;
      }
    }

    if (payment.type === "refund") {
      logger.info(
        `${LOG_PREFIX} 🔄 Generating Generic Credit Memo for POS Refund...`
      );
      try {
        await financeService.updateCustomerPayments({
          id: paymentId,
          metadata: { ...(payment.metadata || {}), qb_sync_status: "creating" },
        });
      } catch (mErr) {}
      const amountAbs = Math.abs(payment.amount as number) / 100;

      const cmResult = await createCreditMemoInQb({
        customerId: qbCustomerId as string,
        date: getBusinessDateString((payment as any).created_at ?? null),
        memo: `Manual Refund / Deposit Return`,
        items: [
          {
            // Generic fallback ID - User must define QB_GENERIC_REFUND_ITEM_ID in .env
            productId:
              process.env.QB_GENERIC_REFUND_ITEM_ID || "80000021-1406822839",
            productName: "Refund",
            quantity: 1,
            price: amountAbs,
            amount: amountAbs,
            desc: "Refund / Generic Store Credit",
          },
        ],
      });

      if (!cmResult.success) {
        logger.error(
          `${LOG_PREFIX} ❌ Failed to create Generic Credit Memo: ${cmResult.error}`
        );
        try {
          await financeService.updateCustomerPayments({
            id: paymentId,
            metadata: { ...(payment.metadata || {}), qb_sync_status: "error" },
          });
        } catch (mErr) {}
        return;
      }

      const opId = cmResult.data?.operationId;
      if (opId) {
        try {
          await financeService.updateCustomerPayments({
            id: paymentId,
            metadata: {
              ...(payment.metadata || {}),
              qb_operation_id: opId,
              qb_sync_status: "synced",
            },
          });
          logger.info(`${LOG_PREFIX} ✅ Generic Credit Memo queued: ${opId}`);
        } catch (err: any) {
          logger.warn(
            `${LOG_PREFIX} ⚠️ Failed to save QB TxnID: ${err.message}`
          );
        }
      }
      return;
    }

    // 3. Register Payment as ReceivePayment in QuickBooks
    // This drops the deposit into QB as an unapplied credit (linked to the correct Customer)
    try {
      await financeService.updateCustomerPayments({
        id: paymentId,
        metadata: { ...(payment.metadata || {}), qb_sync_status: "creating" },
      });
    } catch (mErr) {
      logger.warn(`${LOG_PREFIX} Could not set creating status: ${mErr}`);
    }

    // Pre-flight pipeline row — appears in QB pipeline UI immediately
    const pipelineOrderId = (orderId as string) || null;
    try {
      await writePipelineRow({
        orderId: pipelineOrderId,
        referenceId: paymentId,
        referenceType: "customer_payment",
        step: "payment",
        status: "pending",
        medusaRefNumber: medusaPayRef,
      });
    } catch (pErr: any) {
      logger.warn(
        `${LOG_PREFIX} ⚠️ Could not write pre-flight pipeline row: ${pErr.message}`
      );
    }

    // Resolve the QB PaymentMethod name via the canonical split-aware helper:
    //   - credit_card → send card_brand (Visa/MasterCard/Amex/Discover/Capital One)
    //   - anything else → send payment_method itself (Debit Card / Cash / Check / ...)
    //
    // Legacy fallbacks (bams_card_label, bams_card_type, metadata.card_brand,
    // metadata.pos_payment_method) are only consulted when the canonical
    // payment.method / payment.card_brand are unset — the 2026-04-18 backfill
    // populated both canonical columns, so in steady state the helper's two
    // inputs are enough. The fallback chain stays here purely as belt-and-
    // suspenders for any row that somehow escaped the backfill.
    const canonicalMethod = payment.method as string | undefined;
    const canonicalBrand = (payment as any).card_brand as string | undefined;
    const rawLabel = payment.metadata?.bams_card_label as string | undefined;
    const metaBrand = payment.metadata?.card_brand as string | undefined;
    const rawCardType = payment.metadata?.bams_card_type as string | undefined;
    const rawPosMethod = payment.metadata?.pos_payment_method as
      | string
      | undefined;

    let resolvedQbMethod = resolveQbPaymentMethodForPayment(
      canonicalMethod,
      canonicalBrand ?? metaBrand
    );
    if (!resolvedQbMethod) {
      // Legacy belt-and-suspenders: try the full candidate chain in case the
      // canonical columns were unpopulated (pre-backfill rows or manual inserts).
      resolvedQbMethod = sanitizeToQbPaymentMethod(
        canonicalBrand,
        rawLabel,
        metaBrand,
        rawPosMethod,
        rawCardType,
        canonicalMethod
      );
    }
    if (!resolvedQbMethod) {
      logger.warn(
        `${LOG_PREFIX} ⚠️ Could not resolve QB PaymentMethod for payment ${paymentId} from ` +
          `{method=${canonicalMethod ?? "∅"}, canonical_brand=${canonicalBrand ?? "∅"}, label=${rawLabel ?? "∅"}, ` +
          `meta_brand=${metaBrand ?? "∅"}, cardType=${rawCardType ?? "∅"}, pos_method=${rawPosMethod ?? "∅"}} — ` +
          `sending ReceivePayment without PaymentMethodRef (QB will leave it blank)`
      );
    }

    const result = await processPaymentCaptureInQb({
      orderId: (orderId as string) || `payment_${paymentId}`,
      orderDisplayId:
        parseInt(String(orderDisplayId || "").replace(/\D/g, ""), 10) ||
        undefined,
      amount: (payment.amount as number) / 100,
      paymentMethod: resolvedQbMethod,
      qbCustomerId: qbCustomerId as string,
      memo,
      onSubmitted: async (operationId) => {
        await writePipelineRow({
          orderId: (orderId as string) || null,
          referenceId: paymentId,
          referenceType: "customer_payment",
          step: "payment",
          status: "submitted",
          bridgeOpId: operationId,
        });
      },
    });

    if (result.skipped) {
      logger.info(`${LOG_PREFIX} ⏭️ Skipped: QB disabled or not configured`);
      return;
    }
    if (result.error) {
      logger.error(
        `${LOG_PREFIX} ❌ QB Payment Capture failed: ${result.error}`
      );
      try {
        await financeService.updateCustomerPayments({
          id: paymentId,
          metadata: { ...(payment.metadata || {}), qb_sync_status: "error" },
        });
        await writePipelineRow({
          orderId: pipelineOrderId,
          referenceId: paymentId,
          step: "payment",
          status: "failed",
          error: result.error,
        });
      } catch (mErr) {}
      return;
    }

    // Save QB TxnId to the POS Payment record and confirm pipeline row
    if (result.txnId || result.operationId) {
      try {
        await financeService.updateCustomerPayments({
          id: paymentId,
          metadata: {
            ...(payment.metadata || {}),
            qb_sync_status: "synced",
            qb_txn_id: result.txnId || null,
            qb_operation_id: result.operationId || null,
            qb_memo: memo || null,
          },
        });
        logger.info(
          `${LOG_PREFIX} ✅ Saved QB TxnID=${result.txnId} to POS payment ${paymentId}`
        );
      } catch (err: any) {
        logger.warn(
          `${LOG_PREFIX} ⚠️ Failed to save QB TxnID to payment ${paymentId}: ${err.message}`
        );
      }
      try {
        await writePipelineRow({
          orderId: pipelineOrderId,
          referenceId: paymentId,
          step: "payment",
          status:
            result.operationId && !result.txnId ? "submitted" : "confirmed",
          bridgeOpId: result.operationId || null,
          qbTxnId: result.txnId || null,
          qbRefNumber: result.refNumber || null,
        });
      } catch (pErr: any) {
        logger.warn(
          `${LOG_PREFIX} ⚠️ Could not confirm pipeline row: ${pErr.message}`
        );
      }
      // Cache EditSequence so future ReceivePaymentMod ops (e.g. payment method change)
      // don't need a separate GET round-trip to QB.
      if (result.editSequence && result.txnId) {
        try {
          await cacheEditSequence("payment", result.txnId, result.editSequence);
          logger.info(
            `${LOG_PREFIX} ✅ Cached EditSequence for payment TxnID=${result.txnId}`
          );
        } catch (cErr: any) {
          logger.warn(
            `${LOG_PREFIX} ⚠️ Could not cache EditSequence: ${cErr.message}`
          );
        }
      }
    }

    // 4. Log intention based on deposit_type
    if (depositType === "INVOICE") {
      logger.info(
        `${LOG_PREFIX} ℹ️ Payment is for an INVOICE. The unapplied credit was created successfully. Application to the Invoice will be handled by pos.payment.applied.`
      );
    } else if (depositType === "ORDER") {
      logger.info(
        `${LOG_PREFIX} ℹ️ Payment is for an ORDER. It will sit as unapplied credit until the final Standalone Invoice or Linked Invoice applies it.`
      );
    }
  } catch (err: any) {
    logger.error(`${LOG_PREFIX} ❌ Unhandled exception: ${err.message}`);
    logger.error(err.stack);
    try {
      const financeService = container.resolve(FINANCE_MODULE) as any;
      const paymentId = event.data.id;
      if (paymentId) {
        await financeService.updateCustomerPayments({
          id: paymentId,
          metadata: { qb_sync_status: "error" }, // Will merge natively by module if configured, but we can't reliably read prev metadata here if it crashed early
        });
      }
    } catch (mErr) {
      logger.error(
        `${LOG_PREFIX} Could not save fallback error status: ${mErr}`
      );
    }
  }
}
