#!/usr/bin/env tsx
import { ExecArgs } from "@medusajs/framework/types";
import { ContainerRegistrationKeys, Modules } from "@medusajs/utils";
import { IProductModuleService } from "@medusajs/types";
import * as fs from "fs";
import * as path from "path";

/**
 * sync-qb-sales-descriptions.ts
 *
 * Syncs QB SalesDesc → product.metadata.sales_description for existing Medusa products.
 * Matches by SKU: QB item.sku (FullName) ↔ Medusa variant.sku → product
 * Does NOT create new products. Does NOT modify variants. Safe to run repeatedly.
 *
 * Usage:
 *   # Dry run (preview only — no writes):
 *   npx medusa exec src/scripts/migrate/sync-qb-sales-descriptions.ts -- --dry-run
 *
 *   # Live run (writes to DB):
 *   npx medusa exec src/scripts/migrate/sync-qb-sales-descriptions.ts
 *
 * QB data source:
 *   /tmp/qb-active-products.json (generated by check-qb-active-products.ts)
 *   Run that script first if the file is stale (>24h old).
 */

const QB_DATA_FILE = "/tmp/qb-active-products.json";

// ── HTML entity decoder ──────────────────────────────────────────────────────
function decodeHtmlEntities(str: string): string {
  return str
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(parseInt(code)));
}

export default async function syncQbSalesDescriptions({
  container,
  args,
}: ExecArgs) {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER);
  const query = container.resolve(ContainerRegistrationKeys.QUERY);
  const productModule: IProductModuleService = container.resolve(
    Modules.PRODUCT
  );

  const isDryRun =
    args?.includes("--dry-run") || process.env.DRY_RUN === "true";

  logger.info("=".repeat(60));
  logger.info(
    `🔄 QB Sales Description Sync ${isDryRun ? "[DRY RUN — no writes]" : "[LIVE — writing to DB]"}`
  );
  logger.info("=".repeat(60));

  // ── 1. Load QB data ──────────────────────────────────────────────────────
  if (!fs.existsSync(QB_DATA_FILE)) {
    logger.error(`❌ QB data file not found: ${QB_DATA_FILE}`);
    logger.error(
      `   Run first: npx tsx src/scripts/checks/check-qb-active-products.ts`
    );
    return;
  }

  const qbRaw = JSON.parse(fs.readFileSync(QB_DATA_FILE, "utf8"));
  const qbProducts: any[] = qbRaw.products || [];

  // Build SKU → description map (inventory items only, skip service/discount/etc.)
  const qbDescMap = new Map<string, string>();
  for (const item of qbProducts) {
    const sku = (item.sku || "").trim();
    const desc = (item.description || "").trim();
    if (sku && desc) {
      qbDescMap.set(sku, decodeHtmlEntities(desc));
    }
  }

  logger.info(
    `📦 QB data loaded: ${qbProducts.length} total items, ${qbDescMap.size} with descriptions`
  );

  // ── 2. Load all Medusa variants with their product ───────────────────────
  logger.info(`\n🔍 Fetching all Medusa variants...`);
  const { data: variants } = await query.graph({
    entity: "variant",
    fields: ["id", "sku", "product.id", "product.title", "product.metadata"],
  });

  const variantsWithSku = variants.filter((v: any) => v.sku);
  logger.info(
    `   Found ${variants.length} variants total, ${variantsWithSku.length} with SKU`
  );

  // ── 3. Match variants → QB descriptions ──────────────────────────────────
  // Group by product (a product may have multiple variants → use first match)
  const productUpdates = new Map<
    string,
    {
      productId: string;
      productTitle: string;
      currentDesc: string | null;
      newDesc: string;
      matchedSkus: string[];
    }
  >();

  let noMatch = 0;

  for (const variant of variantsWithSku) {
    const sku = (variant.sku || "").trim();
    const product = (variant as any).product;
    if (!product?.id) continue;

    const qbDesc = qbDescMap.get(sku);
    if (!qbDesc) {
      noMatch++;
      continue;
    }

    if (productUpdates.has(product.id)) {
      // Already found a description for this product — just add the matched SKU
      productUpdates.get(product.id)!.matchedSkus.push(sku);
    } else {
      const currentDesc = (product.metadata as any)?.sales_description || null;
      productUpdates.set(product.id, {
        productId: product.id,
        productTitle: product.title,
        currentDesc,
        newDesc: qbDesc,
        matchedSkus: [sku],
      });
    }
  }

  const toUpdate = [...productUpdates.values()];
  const alreadyGood = toUpdate.filter(
    (u) => u.currentDesc === u.newDesc
  ).length;
  const willChange = toUpdate.filter((u) => u.currentDesc !== u.newDesc);

  logger.info(`\n📊 MATCH RESULTS`);
  logger.info(`   Variants with SKU:       ${variantsWithSku.length}`);
  logger.info(
    `   Variants matched in QB:  ${variantsWithSku.length - noMatch}`
  );
  logger.info(`   Variants NOT in QB:      ${noMatch}`);
  logger.info(`   Products to update:      ${willChange.length}`);
  logger.info(`   Already up-to-date:      ${alreadyGood}`);

  if (willChange.length === 0) {
    logger.info(
      "\n✅ All products already have up-to-date descriptions. Nothing to do."
    );
    return;
  }

  // ── 4. Preview ───────────────────────────────────────────────────────────
  logger.info(`\n📋 PREVIEW (first 20):`);
  logger.info(
    `   ${"PRODUCT TITLE".padEnd(40)} SKU(s)              NEW DESCRIPTION (first 60 chars)`
  );
  logger.info(`   ${"-".repeat(120)}`);

  willChange.slice(0, 20).forEach((u) => {
    const title = (u.productTitle || "").slice(0, 38).padEnd(40);
    const skus = u.matchedSkus.slice(0, 2).join(", ").slice(0, 18).padEnd(20);
    const descPrev = u.newDesc.slice(0, 60);
    const changed = u.currentDesc ? "UPDATE" : "NEW   ";
    logger.info(`   [${changed}] ${title} ${skus} ${descPrev}`);
  });

  if (willChange.length > 20) {
    logger.info(`   ... and ${willChange.length - 20} more`);
  }

  if (isDryRun) {
    logger.info(`\n${"=".repeat(60)}`);
    logger.info(`📊 DRY RUN COMPLETE — no changes written`);
    logger.info(`   Would update: ${willChange.length} products`);
    logger.info(`   To run live:`);
    logger.info(
      `   npx medusa exec src/scripts/migrate/sync-qb-sales-descriptions.ts`
    );
    logger.info("=".repeat(60));
    return;
  }

  // ── 5. Live update ───────────────────────────────────────────────────────
  logger.info(`\n✍️  Updating ${willChange.length} products in Medusa...`);
  let updated = 0;
  let failed = 0;
  const BATCH = 25;

  for (let i = 0; i < willChange.length; i++) {
    const u = willChange[i]!;
    try {
      await productModule.updateProducts(u.productId, {
        metadata: {
          ...(typeof u.currentDesc === "object" ? {} : {}), // preserve other metadata
          sales_description: u.newDesc,
        },
      });
      updated++;
      if (updated % BATCH === 0) {
        logger.info(
          `   ✅ Progress: ${updated}/${willChange.length} updated...`
        );
      }
    } catch (err: any) {
      failed++;
      logger.error(
        `   ❌ Failed to update ${u.productId} (${u.productTitle}): ${err.message}`
      );
    }
  }

  logger.info(`\n${"=".repeat(60)}`);
  logger.info(`✅ SYNC COMPLETE`);
  logger.info(`   Updated:  ${updated} products`);
  logger.info(`   Failed:   ${failed} products`);
  logger.info(`   Skipped:  ${alreadyGood} (already up-to-date)`);
  logger.info(`   No QB match: ${noMatch} variants`);
  logger.info("=".repeat(60));
}
