import { model } from "@medusajs/utils";
/** SQL owns bigint amounts and append-only enforcement; write through accounting-core. */
export const BankJournalEntry = model.define("bank_journal_entry", {
  id: model.id({ prefix: "bje" }).primaryKey(),
  expense_id: model.text().nullable(),
  transaction_id: model.text().nullable(),
  receipt_id: model.text().nullable(),
  deposit_id: model.text().nullable(),
  kind: model.enum([
    "expense",
    "receipt",
    "deposit",
    "payment_match",
    "reversal",
    "movement",
    "merchant_settlement",
    "merchant_receipt",
    "document",
  ]),
  completion_id: model.text().nullable(),
  completion_stage: model.text().nullable(),
  day: model.text(),
  currency: model.text(),
  amount_cents: model.text(),
  source_hash: model.text(),
  source_snapshot: model.json(),
  reference: model.text(),
  description: model.text(),
  actor_id: model.text(),
  reverses_entry_id: model.text().nullable(),
  reason: model.text().nullable(),
  // gl-core-v1: familia `document` (invoice/credit memo/pago/redondeo).
  source_kind: model.text().nullable(),
  source_id: model.text().nullable(),
  document_number: model.text().nullable(),
  posted_by: model.text().nullable(),
});
