#!/bin/bash
# Monitor Railway Deployment

echo "🚂 Monitoring Railway Deployment..."
echo "=================================="
echo ""
echo "📍 Railway Dashboard:"
echo "   https://railway.app/project/your-project-id"
echo ""
echo "🔍 Deployment Logs:"
echo "   1. Go to Railway dashboard"
echo "   2. Click on 'medusa-starter-default' service"
echo "   3. Click on latest deployment"
echo "   4. Watch build logs"
echo ""
echo "⏱️  Expected deployment time: ~3-5 minutes"
echo ""
echo "✅ Deployment will be successful if you see:"
echo "   - 'yarn install' completes (installs medusa-plugin-auth)"
echo "   - 'yarn build' completes"  
echo "   - 'Server is ready on port XXXX'"
echo ""
echo "❌ Common errors to watch for:"
echo "   - Missing env variables (GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET)"
echo "   - Build failures"
echo "   - Database connection issues"
echo ""
echo "🧪 After deployment, test:"
echo ""
echo "# Health check"
curl -s https://medusa-starter-default-production-b69e.up.railway.app/health && echo "✅ Backend is alive!" || echo "❌ Backend not responding"
echo ""
echo ""
echo "# Google OAuth endpoint (should redirect to Google)"
echo "Test in browser: https://medusa-starter-default-production-b69e.up.railway.app/store/auth/google"
echo ""
echo "=================================="
echo "⏳ Waiting for deployment... (refresh Railway dashboard)"
